### ISSUE TITLE
onSlide or currentSlideIndex aren't working

### ISSUE THREAD

**Issue by abhij89** [faceless-ui/slider#5]
I need to change the slide index from 0 to 5 with the click of a card, but it doesn't seem to be working. Here is my code:

```
const Cards = ({ col, i, setIndex }) => {
  const { toggle } = useModal();
  return (
    <div
      onClick={() => {
        toggle('my-modal');
        setIndex(i);
      }}
      key={i}
    >
      ...content
    </div>
  );
};

const SliderComponent = ({ myContent, sliderIndex }) => (
  <div className="slider-main-div">
    <SliderProvider
      onSlide={sliderIndex}
      slidesToShow={1}
    >
      <SliderButton direction="prev">
        Prev
      </SliderButton>
      <SliderTrack>
        {
            myContent?.map(
              (col, i) => (
                <Slide
                  index={i}
                  className={classes.carousel_item}
                >
                  ..content
                </Slide>
              ),
            )
          }
      </SliderTrack>
      <SliderButton direction="next">
        Next
      </SliderButton>
    </SliderProvider>
  </div>
);

export const Component: React.FC<Type> = ({
  myContent,
}) => {
  const [sliderIndex, setIndex] = useState(0);
  return (
    <div
      className={classes.content}
    >
      <ModalProvider transTime={250}>
        <div className={classes.togglediv}>
          <ModalContainer />
          <Modal slug="my-modal">
            <SliderComponent
              myContent={myContent}
              sliderIndex={sliderIndex}
            />
          </Modal>
        </div>
        <GridContainer>
          <div className={classes.projects}>
            {myContent?.map((col, i) => (
              <Cards
                col={col}
                i={i}
                setIndex={(index) => setIndex(index)}
              />
            ))}
          </div>
        </GridContainer>
      </ModalProvider>
    </div>
  );
};
```

So when I am clicking on the card, it triggers the onclick function to open the modal and changes the slider index corresponding to the clicked card. But when the index is updated, the slide isn't changing. Any suggestions? Documentation doesn't have anything.
I double-checked that SliderComponent is getting the correct sliderIndex.

**Comment by jacobsfletch** [comment]
Hi @abhij89 this should be possible, but I do see a couple strange areas in your code. You shouldn't need to maintain `sliderIndex`, but instead, should read this from slider context. You can either use the `useSlider` hook or pass a child function to the slider provider like this:

```
<SliderProvider>
  {(sliderContext) => (
    ...
  )}
</SliderProvider>
```

The other strange part is that `onSlide` method on the `sliderProvider` is being used a prop. You should omit this line.

Lastly, set the new slide index using the `goToSlideIndex` method.

This should get you there, but let me know if you need more help!

**Comment by abhij89** [comment]
@jacobsfletch thank you for the answer. I will definitely improve the code based on your suggestions. Though do you have any examples of how to use or call the `goToSlideIndex` method?

**Comment by jacobsfletch** [comment]
Here's a quick snippet based on your use case:

```
export const Card = ({ index }) => {
  const { goToSlideIndex } = useSlider();
  const { open: openModal } = useModal();

  return (
    <div 
      onClick={() => {
        open('my-modal');
        goToSlideIndex(index);
      }}
    >
      {`This is card ${index + 1}`}
    </div>
  )
}
```

**Comment by abhij89** [comment]
I tried this, but it didn't work. I wrapped the card component inside of sliderProvider and then onClick I used this method `goToSlideIndex(index);` to change the index..it didn't change it when the modal was open it was still at index 0.

**Comment by abhij89** [comment]
Here is my updated code..
```
const Cards = ({ col, i, setSliderIndex }) => {
  const { toggle } = useModal();
  const { goToSlideIndex, goToNextSlide } = useSlider();
  return (
    <div
      data-aos="fade-up"
      data-aos-once="true"
      data-aos-delay={`${i}00`}
      onClick={() => {
        setSliderIndex(i);
        toggle('my-modal');
        goToSlideIndex(7);
        goToNextSlide();
      }}
    >
      ..content
    </div>
  );
};

const SliderComponent = ({ myContent, sliderIndex }) => {
  return (
    <div className="slider-main-div">
    <SliderProvider
      onSlide={sliderIndex}
      slidesToShow={1}
    >
      <SliderButton direction="prev">
        Prev
      </SliderButton>
      <SliderTrack>
        {
            myContent?.map(
              (col, i) => (
                <Slide
                  index={i}
                  className={classes.carousel_item}
                >
                  ..content
                </Slide>
              ),
            )
          }
      </SliderTrack>
      <SliderButton direction="next">
        Next
      </SliderButton>
    </SliderProvider>
    </div>
  );
};

export const Component: React.FC<Type> = ({
  myContent,
}) => {
  const [sliderIndex, setSliderIndex] = useState(0);
  return (
    <div
      className={classes.content}
    >
      <h4
        className={classes.roadmap_section_title}
        data-aos="fade-up"
        data-aos-once="true"
      >
        Roadmap
      </h4>
      <ModalProvider transTime={250}>
        <div className={classes.togglediv}>
          <ModalContainer />
          <Modal slug="my-modal">
            <SliderComponent
                roadmap={roadmap}
                sliderIndex={sliderIndex}
              />
          </Modal>
        </div>
        <GridContainer>
          <SliderProvider>
            <div className={classes.projects}>
              {myContent?.map((col, i) => (
                <Cards
                  col={col}
                  i={i}
                  setSliderIndex={(index) => setSliderIndex(index)}
                />
              ))}
            </div>
          </SliderProvider>
        </GridContainer>
      </ModalProvider>
    </div>
  );
};

export default Roadmap;

```

**Comment by jacobsfletch** [comment]
Yea it still isn't quite as I described. I went ahead and wrote this out for you:

```
const modalTransTime = 250;

const Card = ({ index }) => {
    const { goToSlideIndex } = useSlider();
    const { open: openModal } = useModal();

    return (
        <div 
            onClick={() => {
                openModal('my-modal');
                setTimeout(() => {
                    goToSlideIndex(index);
                }, modalTransTime); // the modal has to open first
            }}
        >
            {`This is card ${index + 1}`}
        </div>
    )
}

const SliderComponent = ({ myContent }) => {
  return (
    <div className="slider-main-div">
        <SliderProvider slidesToShow={1}>
            <SliderButton direction="prev">
                Prev
            </SliderButton>
            <SliderTrack>
                {myContent?.map((content, i) => (
                    <Slide
                        index={i}
                        key={i}
                        className={classes.carousel_item}
                    >
                        <Card index={i}>
                            {...content}
                        </Card>
                    </Slide>
                ))}
            </SliderTrack>
            <SliderButton direction="next">
                Next
            </SliderButton>
        </SliderProvider>
    </div>
  );
};

export const Component: React.FC<Type> = ({
  myContent,
}) => {

  return (
    <div
      className={classes.content}
    >
      <h4
        className={classes.roadmap_section_title}
        data-aos="fade-up"
        data-aos-once="true"
      >
        Roadmap
      </h4>
      <ModalProvider transTime={modalTransTime}>
        <div className={classes.togglediv}>
          <ModalContainer />
          <Modal slug="my-modal">
            <SliderComponent myContent={myContent} />
          </Modal>
        </div>
        <GridContainer>
          <SliderComponent myContent={myContent} />
        </GridContainer>
      </ModalProvider>
    </div>
  );
};

export default Roadmap;
```

**Comment by abhij89** [comment]
@jacobsfletch yeah, I tried the timeout, but it didn't work. To make sure that setTimeout is working I added console.log in it and that worked fine and logged the message but function `goToSlideIndex` didn't work.

**Comment by jacobsfletch** [comment]
@abhij89 this should work, so something must be getting lost in implementation. If you can spin up CodeSandbox, I am more than happy to help get it in a working state for you there.

**Comment by abhij89** [comment]
I can get you access to the repo which has the above code. @jacobsfletch is the username, right? Is it ok to send you an invite?

**Comment by jacobsfletch** [comment]
I would prefer a [SandBox](https://codesandbox.io/), this way your issue is isolated and I wouldn't have to spin up your app. The snippet above is 99% of the what is needed to make that happen. It should be pretty easy to set up, but if you're having troubles I might be able to do this for you at some point.

**Comment by jacobsfletch** [comment]
Hey @abhij89! I just published a new version with fixes to both `currentSlideIndex` props and the `goToSlideIndex` method. Go ahead and run `yarn add @faceles-ui/slider@^1.1.5` and let me know if that helps you out.

I am also working on example sliders that I will publish to the website once ready. This will include various types of sliders along with their source code. This will help everyone tremendously.

Let me know how it goes with `v1.1.5`!

**Comment by jacobsfletch** [comment]
Hey @abhij89! As promised, here's a [live working example](https://www.faceless-ui.com/docs/slider/examples/lightbox-slider).

**Comment by abhij89** [comment]
@jacobsfletch source code link is wrong on the live working example page. You probably linked it with private repo instead of the public one, can you update that?

**Comment by abhij89** [comment]
Thank you for the fix and updating the code. @jacobsfletch

**Comment by jacobsfletch** [comment]
@abhij89 good catch, got that linked fix up now 😄 . Give it another shot!

**Comment by abhij89** [comment]
@jacobsfletch hey, I tried the example but it still didn't work, I have the same code as yours but it still doesn't change the index. I can see the `currentSlideIndex` changing for the slider inside the modal when clicking the slide of the slider outside but it still isn't scrolling to the right index..can you suggest why it would do that? I have the latest version.

**Comment by jacobsfletch** [comment]
Hi @abhij89 found the problem and published a `v1.1.8` just now! Thank you for reporting that. Install that version, and all should be well. To make sure of this, [I made this CodeSandbox](https://codesandbox.io/s/lightbox-slider-0m8tyu). It's a live, working demo of a lightbox slider.

Hope this helps!!

**Comment by jacobsfletch** [comment]
@abhij89 ok wow `v1.1.8` isn't quite there yet either, my apologies. I'm publishing another version shortly.

**Comment by abhij89** [comment]
Finally!!!! It's working now. Thank you for fixing this. Appreciate it. @jacobsfletch

**Comment by jacobsfletch** [comment]
@abhij89 CodeSandbox appears to be slow in getting the latest version, so I went ahead and deployed the [a similar example to the docs directly](https://www.faceless-ui.com/docs/slider/examples/lightbox).

**Comment by abhij89** [comment]
Thank you, I already tried locally and it works.
