### ISSUE TITLE
Snap Slider causes drag functionality to not work

### ISSUE THREAD

**Issue by TomSmedley** [faceless-ui/slider#8]
Hey guys,

I'm loving Payload and I thought I'd give Faceless UI a try and I'm after a pretty basic slider just to handle tabs that overflow, this looks like a great fit. I've noticed that Snap Slider causes drag to fail https://facelessui.com/docs/slider/examples/snap

**Comment by jacobsfletch** [comment]
Hey @TomSmedley! Good catch, that is definitely not behaving as expected. We'll get this patched up for you. Stay tuned!

**Comment by jacobsfletch** [comment]
Hey @TomSmedley! The linked PR closed this ticket automatically, so I wanted to quickly follow-up with you here. I just  published `v1.1.13` which fixes this issue. The [Snap Slider](https://facelessui.com/docs/slider/examples/snap) demo on the website has been updated to reflect this fix. Take a look!

Here's a quick snippet to get installed in your project:

```
yarn add @faceless-ui/modal@^1.1.13
```

Let me know how it goes and THANK YOU for reporting this.
